ba.uz/2-module/Django/36-dars/balita/blog/urls.py
from django.urls import path

from .views import home_view, about_view, categories_view, contact_view, article_info, tag_view, search_view

urlpatterns = [
    path('', home_view),
    path('about/', about_view),
    path('categories/', tag_view),
    path('categories/<int:pk>', categories_view),
    path('contact/', contact_view),
    path('category/<int:pk>', article_info),
    path('search/', search_view),
]

ba.uz/2-module/Django/36-dars/balita/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ba.uz/2-module/Django/36-dars/balita/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=70)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = RichTextField()
    image = models.ImageField(upload_to='articles/')
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    is_published = models.BooleanField(default=True)
    view_count = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_title(self):
        return self.title

    def get_desc(self):
        return self.description

    def __str__(self):
        return self.title


class Comments(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    telegram = models.CharField(max_length=255, blank=True, null=True)
    comment = RichTextField()
    is_visiable = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    message = RichTextField()
    is_responded = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ba.uz/2-module/Django/36-dars/balita/blog/views.py
from django.shortcuts import render, redirect
from .models import Article, Category, Comments, Tag, Contact
from django.core.paginator import Paginator
from django.db.models import Q
from .search import search

categories = Category.objects.all()


# Create your views here.

def home_view(request):
    data = request.GET
    page = data.get('page', 1)

    categories = Category.objects.all()
    articles = Article.objects.all().order_by('category', '-created_at')
    page_obj = Paginator(articles, 4)
    popular = Article.objects.all().order_by('-view_count')
    vc = popular[(len(popular) // 2)].view_count
    more_blog_posts = Article.objects.filter(view_count__lte=vc).order_by('-created_at')
    popular_article = Article.objects.all().order_by('-created_at')
    tags = Tag.objects.all()
    d = {
        "home": "active",
        "categories": categories,
        "slider_article": articles[3:(len(articles) - 3)],
        "popular_article": popular_article[:3],
        "articles": page_obj.get_page(page),
        "more_blog_posts": more_blog_posts[:3],
        "popular": popular[:3],
        "tags": tags,
        "latests_footer": popular_article[:3]
    }
    return render(request, 'index.html', context=d)


def about_view(request):
    data = request.GET
    latest = Article.objects.all().order_by('-created_at')
    page = data.get('page', 1)
    page_article = Paginator(latest, 3)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    popular = Article.objects.all().order_by('-view_count')
    d = {
        "about": "active",
        "categories": categories,
        "popular": popular[:3],
        "tags": tags,
        "latest": page_article.get_page(page),
        "latests_footer": latest[:3]
    }
    return render(request, 'about.html', context=d)


def tag_view(request):
    data = request.GET
    tag = data.get('tag', None)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    popular = Article.objects.all().order_by('-view_count')
    cat_name = Tag.objects.filter(id=int(tag))
    latest = Article.objects.all().order_by('-created_at')
    if tag != None:
        articles = Article.objects.filter(tags=int(tag))
        d = {
            "articles": articles,
            "category": "active",
            "categories": categories,
            "cat_name": cat_name[0],
            "popular": popular[:3],
            "tags": tags,
            "latests_footer": latest[:3]
        }
        return render(request, 'category.html', context=d)


def categories_view(request, pk):
    data = request.GET
    articles = Article.objects.filter(category=pk)
    page = data.get('page', 1)
    page_obj = Paginator(articles, 6)
    categories = Category.objects.all()
    cat_name = Category.objects.filter(id=pk)
    tags = Tag.objects.all()
    popular = Article.objects.all().order_by('-view_count')
    latest = Article.objects.all().order_by('-created_at')
    d = {
        "articles": page_obj.get_page(page),
        "category": "active",
        "categories": categories,
        "cat_name": cat_name[0],
        "popular": popular[:3],
        "tags": tags,
        "latests_footer": latest[:3]
    }
    return render(request, 'category.html', context=d)


def article_info(request, pk):
    if request.method == "POST":
        comment = request.POST
        obj = Comments.objects.create(name=comment['name'], email=comment['email'], telegram=comment['telegram'],
                                      comment=comment['comment'], article_id=pk)
        obj.save()
        return redirect(f'/category/{pk}')

    detail = Article.objects.filter(id=pk).first()
    detail.view_count += 1
    comments = Comments.objects.filter(article_id=pk, is_visiable=True)
    detail.save(update_fields=['view_count'])
    popular = Article.objects.all().order_by('-view_count')
    tags = Tag.objects.all()
    reletad_tag = [i for i in detail.tags.all()]
    latest = Article.objects.all().order_by('-created_at')

    d = {
        "category": "active",
        "categories": categories,
        "comments": comments,
        "detail": detail,
        "len_comment": len(comments),
        "popular": popular[:3],
        "tags": tags,
        "latests_footer": latest[:3]
    }
    return render(request, 'blog-single.html', context=d)


def contact_view(request):
    if request.method == "POST":
        data = request.POST
        contact_data = Contact.objects.create(name=data['name'], phone=data['phone'], email=data['email'],
                                              message=data['message'])
        contact_data.save()
        return redirect('/contact')
    popular = Article.objects.all().order_by('-view_count')
    latest = Article.objects.all().order_by('-created_at')
    tags = Tag.objects.all()
    d = {
        "contact": "active",
        "categories": categories,
        "popular": popular[:3],
        "tags": tags,
        "latests_footer": latest[:3]
    }
    return render(request, 'contact.html', context=d)


def search_view(request):
    if request.method == "POST":
        data = request.POST
        query = data['key_word']
        return redirect(f'/search?q={query}')
    query = request.GET.get('q')
    if query is not None and len(query) >= 1:
        articles = Article.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
    else:
        articles = Article.objects.filter(is_published=True)

    page = request.GET.get('page', 1)
    page_obj = Paginator(articles, 6)
    tags = Tag.objects.all()
    popular = Article.objects.all().order_by('-view_count')
    latest = Article.objects.all().order_by('-created_at')

    d = {
        "articles": page_obj.get_page(page),
        "category": "active",
        "categories": Category.objects.all(),
        "popular": popular[:3],
        "cat_name": query,
        "tags": tags,
        "latests_footer": latest
    }
    return render(request, 'category.html', context=d)

ba.uz/2-module/Django/36-dars/balita/templates/about.html
{% extends 'layouts/master.html' %}
{% load static %}
{% block title%}
About
{% endblock %}


{% block content %}
<div class="col-md-12 col-lg-8 main-content">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-4">Hi There! I'm Meagan Smith</h2>
            <p class="mb-5"><img src="{% static 'images/img_6.jpg' %}" alt="Image placeholder"
                                 class="img-fluid"></p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum minima eveniet recusandae
                suscipit eum laboriosam fugit amet deleniti iste et. Ad dolores, necessitatibus non saepe
                tenetur impedit commodi quibusdam natus repellat, exercitationem accusantium perferendis
                officiis. Laboriosam impedit quia minus pariatur!</p>
            <p>Dignissimos iste consectetur, nemo magnam nulla suscipit eius quibusdam, quo aperiam quia
                quae est explicabo nostrum ab aliquid vitae obcaecati tenetur beatae animi fugiat officia id
                ipsam sint? Obcaecati ea nisi fugit assumenda error totam molestiae saepe fugiat officiis
                quam?</p>
            <p>Culpa porro quod doloribus dolore sint. Distinctio facilis ullam voluptas nemo voluptatum
                saepe repudiandae adipisci officiis, explicabo eaque itaque sed necessitatibus, fuga, ea
                eius et aliquam dignissimos repellendus impedit pariatur voluptates. Dicta perferendis
                assumenda, nihil placeat, illum quibusdam. Vel, incidunt?</p>
            <p>Dolorum blanditiis illum quo quaerat, possimus praesentium perferendis! Quod autem optio
                nobis, placeat officiis dolorem praesentium odit. Vel, cum, a. Adipisci eligendi eaque
                laudantium dicta tenetur quod, pariatur sunt sed natus officia fuga accusamus reprehenderit
                ratione, provident possimus ut voluptatum.</p>
        </div>
    </div>
    <div class="row mb-5 mt-5">
        <div class="col-md-12 mb-5">
            <h2>My Latest Posts</h2>
        </div>
        <div class="col-md-12">
            {% for article in latest %}
            <div class="post-entry-horzontal">
                <a href="/category/{{article.id}}">
                    <div class="image" style="background-image: url({{article.image.url}});"></div>
                    <span class="text">
<div class="post-meta">
<span class="category">{{article.category}}</span>
<span class="mr-2">{{article.created_at}} </span> &bullet;
<span class="ml-2"><span class="fa fa-comments"></span> 3</span>
</div>
<h2>{{article.title}}</h2>
</span>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation" class="text-center">
                <ul class="pagination">
                    {% if latest.has_previous %}
                    <li class="page-item "><a class="page-link" href="?page={{latest.previous_page_number}}">Prev</a>
                    </li>
                    {% else %}
                    <li class="page-item "><a class="page-link" href="">Prev</a>
                    </li>
                    {% endif %}
                    {% for i in latest.paginator.page_range %}
                    {% if latest.number == i %}
                    <li class="page-item active"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% else%}
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if latest.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{latest.next_page_number}}">Next</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

ba.uz/2-module/Django/36-dars/balita/templates/blog-single.html
{% extends 'layouts/master.html' %}
{% load static %}
{% block title %}
Article
{% endblock %}


{% block content %}
<div class="col-md-12 col-lg-8 main-content">
    <h1 class="mb-4">{{detail.title}}</h1>
    <div class="post-meta">
        <span class="category">{{detail.category}}</span>
        <span class="mr-2">{{detail.created_at}} </span> &bullet;
        <span class="ml-2"><span class="fa fa-comments"></span> {{detail.comments_set.count}}</span>
    </div>
    <div class="post-content-body">
        <p>{{detail.description | safe}}</p>
    </div>
    <div class="pt-5">
        <p>
            Categories:<a href="#">{{detail.category}}</a>
            Tags:
            {% for tag in detail.tags.all %}
            <a href="/categories/?tag={{tag.id}}">#{{ tag }}</a>
            {% endfor %}
        </p>
    </div>
    <div class="pt-5">
        <h3 class="mb-5">{{len_comment}} Comments</h3>
        <ul class="comment-list">
            {% for comment in comments %}
            <li class="comment">
                <div class="vcard">
                    <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                </div>
                <div class="comment-body">
                    <h3>{{comment.name}}</h3>
                    <div class="meta">{{comment.created_at}}</div>
                    <p>{{comment.comment}}</p>
                    <p><a href="#" class="reply">Reply</a></p>
                </div>
            </li>
            {% endfor %}
        </ul>

        <div class="comment-form-wrap pt-5">
            <h3 class="mb-5">Leave a comment</h3>
            <form action="#" class="p-5 bg-light" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Name *</label>
                    <input name="name" type="text" class="form-control" id="name">
                </div>
                <div class="form-group">
                    <label for="email">Email *</label>
                    <input name="email" type="email" class="form-control" id="email">
                </div>
                <div class="form-group">
                    <label for="telegram">Telegram</label>
                    <input name="telegram" type="text" class="form-control" id="telegram">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea name="comment" id="message" cols="30" rows="10" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block related_article %}
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="mb-3 ">Related Post</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <a href="#" class="a-block d-flex align-items-center height-md"
                   style="background-image: url('{% static 'images/img_2.jpg' %}'); ">
                    <div class="text">
                        <div class="post-meta">
                            <span class="category">Lifestyle</span>
                            <span class="mr-2">March 15, 2018 </span> &bullet;
                            <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        </div>
                        <h3>There’s a Cool New Way for Men to Wear Socks and Sandals</h3>
                    </div>
                </a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a href="#" class="a-block d-flex align-items-center height-md"
                   style="background-image: url('{% static 'images/img_3.jpg' %}'); ">
                    <div class="text">
                        <div class="post-meta">
                            <span class="category">Travel</span>
                            <span class="mr-2">March 15, 2018 </span> &bullet;
                            <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        </div>
                        <h3>There’s a Cool New Way for Men to Wear Socks and Sandals</h3>
                    </div>
                </a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a href="#" class="a-block d-flex align-items-center height-md"
                   style="background-image: url('{% static 'images/img_4.jpg' %}'); ">
                    <div class="text">
                        <div class="post-meta">
                            <span class="category">Food</span>
                            <span class="mr-2">March 15, 2018 </span> &bullet;
                            <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        </div>
                        <h3>There’s a Cool New Way for Men to Wear Socks and Sandals</h3>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ba.uz/2-module/Django/36-dars/balita/templates/blog.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
    <title>404 Not Found</title>
    <script nonce="b38160dd-4e40-47c4-be8c-7f1bbbc6c98c">
        try{(function(w,d){!function(j,k,l,m){j[l]=j[l]||{};j[l].executed=[];j.zaraz={deferred:[],listeners:[]};j.zaraz.q=[];j.zaraz._f=function(n){return async function(){var o=Array.prototype.slice.call(arguments);j.zaraz.q.push({m:n,a:o})}};for(const p of["track","set","debug"])j.zaraz[p]=j.zaraz._f(p);j.zaraz.init=()=>{var q=k.getElementsByTagName(m)[0],r=k.createElement(m),s=k.getElementsByTagName("title")[0];s&&(j[l].t=k.getElementsByTagName("title")[0].text);j[l].x=Math.random();j[l].w=j.screen.width;j[l].h=j.screen.height;j[l].j=j.innerHeight;j[l].e=j.innerWidth;j[l].l=j.location.href;j[l].r=k.referrer;j[l].k=j.screen.colorDepth;j[l].n=k.characterSet;j[l].o=(new Date).getTimezoneOffset();if(j.dataLayer)for(const w of Object.entries(Object.entries(dataLayer).reduce(((x,y)=>({...x[1],...y[1]})),{})))zaraz.set(w[0],w[1],{scope:"page"});j[l].q=[];for(;j.zaraz.q.length;){const z=j.zaraz.q.shift();j[l].q.push(z)}r.defer=!0;for(const A of[localStorage,sessionStorage])Object.keys(A||{}).filter((C=>C.startsWith("_zaraz_"))).forEach((B=>{try{j[l]["z_"+B.slice(7)]=JSON.parse(A.getItem(B))}catch{j[l]["z_"+B.slice(7)]=A.getItem(B)}}));r.referrerPolicy="origin";r.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(j[l])));q.parentNode.insertBefore(r,q)};["complete","interactive"].includes(k.readyState)?zaraz.init():j.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document)}catch(e){throw fetch("/cdn-cgi/zaraz/t"),e;};
    </script>
</head>
<body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at preview.colorlib.com Port 443</address>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317"
        integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA=="
        data-cf-beacon='{"rayId":"858fe3ffcdf10974","b":1,"version":"2024.2.1","token":"cd0b4b3a733644fc843ef0b185f98241"}'
        crossorigin="anonymous"></script>
</body>
</html>

ba.uz/2-module/Django/36-dars/balita/templates/category.html
{% extends 'layouts/master.html' %}
{% load static %}
{% block title %}
Categories
{% endblock %}
{% block mainpage_categories_title %}
<div class="row mb-4">
    <div class="col-md-6">
        <h2 class="mb-4">Category: {{cat_name}}</h2>
    </div>
</div>
{% endblock %}
{% block content %}


<div class="col-md-12 col-lg-8 main-content">
    <div class="row mb-5 mt-5">
        <div class="col-md-12">
            {% for article in articles %}
            <div class="post-entry-horzontal">
                <a href="/category/{{article.id}}">
                    <div class="image element-animate" data-animate-effect="fadeIn"
                         style="background-image: url({{article.image.url}});"></div>
                    <span class="text">
                        <div class="post-meta">
                        <span class="category">{{article.category}}</span>
                        <span class="mr-2">{{article.created_at}} </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> {{article.comments_set.count}}</span>
                        </div>
                        <h2>{{article.title}}</h2>
                        </span>
                </a>
            </div>
            {% endfor %}


        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation" class="text-center">
                <ul class="pagination">
                    {% if articles.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{articles.previous_page_number}}">Prev</a>
                    </li>
                    {% endif %}
                    {% for i in articles.paginator.page_range %}
                    {% if articles.number == i %}
                    <li class="page-item active"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if articles.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{articles.next_page_number}}">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

ba.uz/2-module/Django/36-dars/balita/templates/contact.html
{% extends 'layouts/master.html' %}
{% load static %}
{% block title %}
Contact
{% endblock %}

{% block mainpage_categories_title %}
<div class="row mb-4">
    <div class="col-md-6">
        <h1>Contact</h1>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="col-md-12 col-lg-8 main-content">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 form-group">
                <label for="name">Name</label>
                <input name="name" type="text" id="name" class="form-control ">
            </div>
            <div class="col-md-4 form-group">
                <label for="phone">Phone</label>
                <input name="phone" type="text" id="phone" class="form-control ">
            </div>
            <div class="col-md-4 form-group">
                <label for="email">Email</label>
                <input name="email" type="email" id="email" class="form-control ">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 form-group">
                <label for="message">Write Message</label>
                <textarea name="message" id="message" class="form-control " cols="30" rows="8"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 form-group">
                <input type="submit" value="Send Message" class="btn btn-primary">
            </div>
        </div>
    </form>
</div>
{% endblock %}

ba.uz/2-module/Django/36-dars/balita/templates/index.html
{% extends "layouts/master.html" %}
{% load static %}
{% block title %}
Home page
{% endblock %}


{% block slider %}
<div class="row">
    <div class="col-md-12">
        <div class="owl-carousel owl-theme home-slider">
            {% for article in slider_article %}
            <div>
                <a href="/category/{{article.id}}" class="a-block d-flex align-items-center height-lg"
                   style="background-image: url({{article.image.url}}); ">
                    <div class="text half-to-full">
                        <div class="post-meta">
                            <span class="category ">{{article.category}}</span>
                            <span class="mr-2">{{article.created_at}} </span> &bullet;
                            <span class="ml-2"><span
                                    class="fa fa-comments"></span> {{article.comments_set.count}}</span>
                        </div>
                        <h3>{{article.title}}</h3>
                        <p>{{article.sub_title|slice:":100"}}...</p>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}
{% block popular_content%}
<div class="row">
    {% for article in popular_article %}
    <div class="col-md-6 col-lg-4">
        <a href="/category/{{article.id}}" class="a-block d-flex align-items-center height-md"
           style="background-image: url({{article.image.url}}); ">
            <div class="text">
                <div class="post-meta">
                    <span class="category">{{article.category}}</span>
                    <span class="mr-2">{{article.created_at}} </span> &bullet;
                    <span class="ml-2"><span class="fa fa-comments"></span> {{article.comments_set.count}}</span>
                </div>
                <h3>{{article.title}}</h3>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}
{% block mainpage_categories_title %}
<div class="row">
    <div class="col-md-6">
        <h2 class="mb-4">Lifestyle Category</h2>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="col-md-12 col-lg-8 main-content">
    <div class="row">
        {% for article in articles %}
        <div class="col-md-6">
            <a href="/category/{{article.id}}" class="blog-entry element-animate" data-animate-effect="fadeIn">
                <img src="{{article.image.url}}" alt="Image placeholder">
                <div class="blog-content-body">
                    <div class="post-meta">
                        <span class="category">{{article.category}}</span>
                        <span class="mr-2">{{article.updated_at}} </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> {{article.comments_set.count}}</span>
                    </div>
                    <h2>{{article.title}}</h2>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation" class="text-center">
                <ul class="pagination">
                    {% if articles.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{articles.previous_page_number}}">Prev</a>
                    </li>
                    {% else %}
                    <li class="page-item"><a class="page-link">Prev</a></li>
                    {% endif %}
                    {% for i in articles.paginator.page_range %}
                    {% if articles.number == i %}
                    <li class="page-item active"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if articles.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{articles.next_page_number}}">Next</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    <div class="row mb-5 mt-5">
        <div class="col-md-12">
            <h2 class="mb-4">More Blog Posts</h2>
        </div>
        <div class="col-md-12">
            {% for post in more_blog_posts %}
            <div class="post-entry-horzontal">
                <a href="/category/{{post.id}}">
                    <div class="image element-animate" data-animate-effect="fadeIn"
                         style="background-image: url({{post.image.url}});"></div>
                    <span class="text">
<div class="post-meta">
<span class="category">{{post.category}}</span>
<span class="mr-2">{{post.created_at}} </span> &bullet;
<span class="ml-2"><span class="fa fa-comments"></span> {{post.comments_set.count}}</span>
</div>
<h2>{{post.title}}</h2>
</span>
                </a>
            </div>

            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}